// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ConventionPresetCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        convention: {
            type: 'string',
            maxLength: 500,
            title: 'Convention'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        }
    },
    type: 'object',
    required: ['name', 'convention'],
    title: 'ConventionPresetCreate'
} as const;

export const ConventionPresetPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        convention: {
            type: 'string',
            maxLength: 500,
            title: 'Convention'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'convention', 'id'],
    title: 'ConventionPresetPublic'
} as const;

export const ConventionPresetUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        convention: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Convention'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        }
    },
    type: 'object',
    title: 'ConventionPresetUpdate'
} as const;

export const ConventionPresetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ConventionPresetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ConventionPresetsPublic'
} as const;

export const DriveFileSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        modified_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Modified Time'
        },
        thumbnail_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thumbnail Url'
        }
    },
    type: 'object',
    required: ['id', 'name', 'mime_type'],
    title: 'DriveFile'
} as const;

export const DriveFileListSchema = {
    properties: {
        files: {
            items: {
                '$ref': '#/components/schemas/DriveFile'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'DriveFileList'
} as const;

export const DriveFolderSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created Time'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'DriveFolder'
} as const;

export const DriveFolderListSchema = {
    properties: {
        folders: {
            items: {
                '$ref': '#/components/schemas/DriveFolder'
            },
            type: 'array',
            title: 'Folders'
        }
    },
    type: 'object',
    required: ['folders'],
    title: 'DriveFolderList'
} as const;

export const DriveFolderSearchResultSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        parent_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'DriveFolderSearchResult'
} as const;

export const DriveFolderSearchResultListSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/DriveFolderSearchResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'DriveFolderSearchResultList'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RenameConfirmItemSchema = {
    properties: {
        file_id: {
            type: 'string',
            title: 'File Id'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        },
        original_name: {
            type: 'string',
            title: 'Original Name',
            default: ''
        }
    },
    type: 'object',
    required: ['file_id', 'new_name'],
    title: 'RenameConfirmItem'
} as const;

export const RenameConfirmRequestSchema = {
    properties: {
        folder_id: {
            type: 'string',
            title: 'Folder Id'
        },
        renames: {
            items: {
                '$ref': '#/components/schemas/RenameConfirmItem'
            },
            type: 'array',
            title: 'Renames'
        }
    },
    type: 'object',
    required: ['folder_id', 'renames'],
    title: 'RenameConfirmRequest'
} as const;

export const RenameConfirmResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/RenameResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'RenameConfirmResponse'
} as const;

export const RenameHistoryResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RenameLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RenameHistoryResponse'
} as const;

export const RenameLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        folder_id: {
            type: 'string',
            title: 'Folder Id'
        },
        original_name: {
            type: 'string',
            title: 'Original Name'
        },
        new_name: {
            type: 'string',
            title: 'New Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'folder_id', 'original_name', 'new_name'],
    title: 'RenameLogPublic'
} as const;

export const RenamePreviewSchema = {
    properties: {
        file_id: {
            type: 'string',
            title: 'File Id'
        },
        original_name: {
            type: 'string',
            title: 'Original Name'
        },
        proposed_name: {
            type: 'string',
            title: 'Proposed Name'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['file_id', 'original_name', 'proposed_name'],
    title: 'RenamePreview'
} as const;

export const RenamePreviewRequestSchema = {
    properties: {
        folder_id: {
            type: 'string',
            title: 'Folder Id'
        },
        convention: {
            type: 'string',
            title: 'Convention'
        },
        instruction: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instruction'
        },
        content_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Type'
        }
    },
    type: 'object',
    required: ['folder_id', 'convention'],
    title: 'RenamePreviewRequest'
} as const;

export const RenamePreviewResponseSchema = {
    properties: {
        previews: {
            items: {
                '$ref': '#/components/schemas/RenamePreview'
            },
            type: 'array',
            title: 'Previews'
        }
    },
    type: 'object',
    required: ['previews'],
    title: 'RenamePreviewResponse'
} as const;

export const RenameResultSchema = {
    properties: {
        file_id: {
            type: 'string',
            title: 'File Id'
        },
        success: {
            type: 'boolean',
            title: 'Success'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['file_id', 'success'],
    title: 'RenameResult'
} as const;

export const ServiceAccountCreateSchema = {
    properties: {
        display_name: {
            type: 'string',
            maxLength: 255,
            title: 'Display Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        credentials_json: {
            type: 'string',
            title: 'Credentials Json'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['display_name', 'credentials_json', 'user_id'],
    title: 'ServiceAccountCreate'
} as const;

export const ServiceAccountPublicSchema = {
    properties: {
        display_name: {
            type: 'string',
            maxLength: 255,
            title: 'Display Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['display_name', 'id', 'user_id'],
    title: 'ServiceAccountPublic'
} as const;

export const ServiceAccountPublicWithEmailSchema = {
    properties: {
        display_name: {
            type: 'string',
            maxLength: 255,
            title: 'Display Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        client_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Email'
        }
    },
    type: 'object',
    required: ['display_name', 'id', 'user_id'],
    title: 'ServiceAccountPublicWithEmail'
} as const;

export const ServiceAccountUpdateSchema = {
    properties: {
        display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        credentials_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Credentials Json'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        }
    },
    type: 'object',
    title: 'ServiceAccountUpdate'
} as const;

export const ServiceAccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServiceAccountPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServiceAccountsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UsageSummarySchema = {
    properties: {
        requests_today: {
            type: 'integer',
            title: 'Requests Today'
        },
        tokens_this_month: {
            type: 'integer',
            title: 'Tokens This Month'
        },
        limit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserLimitPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['requests_today', 'tokens_this_month'],
    title: 'UsageSummary'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'viewer'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserLimitPublicSchema = {
    properties: {
        max_requests_per_day: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Requests Per Day'
        },
        max_tokens_per_month: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Tokens Per Month'
        }
    },
    type: 'object',
    title: 'UserLimitPublic'
} as const;

export const UserLimitUpdateSchema = {
    properties: {
        max_requests_per_day: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Requests Per Day'
        },
        max_tokens_per_month: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Tokens Per Month'
        }
    },
    type: 'object',
    title: 'UserLimitUpdate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'viewer'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'user', 'viewer'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'viewer'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;