// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DriveReadFoldersResponse, DriveReadFolderFilesData, DriveReadFolderFilesResponse, DriveReadFileMetadataData, DriveReadFileMetadataResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PresetsReadPresetsData, PresetsReadPresetsResponse, PresetsCreatePresetData, PresetsCreatePresetResponse, PresetsUpdatePresetData, PresetsUpdatePresetResponse, PresetsDeletePresetData, PresetsDeletePresetResponse, PrivateCreateUserData, PrivateCreateUserResponse, RenameRenamePreviewData, RenameRenamePreviewResponse, RenameRenameConfirmData, RenameRenameConfirmResponse, ServiceAccountsReadServiceAccountsData, ServiceAccountsReadServiceAccountsResponse, ServiceAccountsCreateServiceAccountData, ServiceAccountsCreateServiceAccountResponse, ServiceAccountsReadOwnServiceAccountResponse, ServiceAccountsReadServiceAccountData, ServiceAccountsReadServiceAccountResponse, ServiceAccountsUpdateServiceAccountData, ServiceAccountsUpdateServiceAccountResponse, ServiceAccountsDeleteServiceAccountData, ServiceAccountsDeleteServiceAccountResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UsersReadUserLimitsData, UsersReadUserLimitsResponse, UsersUpdateUserLimitsData, UsersUpdateUserLimitsResponse, UsersReadUserUsageData, UsersReadUserUsageResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DriveService {
    /**
     * Read Folders
     * List folders accessible by the current user's service account.
     * @returns DriveFolderList Successful Response
     * @throws ApiError
     */
    public static readFolders(): CancelablePromise<DriveReadFoldersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drive/folders'
        });
    }
    
    /**
     * Read Folder Files
     * List files in a specific folder (non-recursive).
     * @param data The data for the request.
     * @param data.folderId
     * @returns DriveFileList Successful Response
     * @throws ApiError
     */
    public static readFolderFiles(data: DriveReadFolderFilesData): CancelablePromise<DriveReadFolderFilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drive/folders/{folder_id}/files',
            path: {
                folder_id: data.folderId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read File Metadata
     * Get metadata for a specific file.
     * @param data The data for the request.
     * @param data.fileId
     * @returns DriveFile Successful Response
     * @throws ApiError
     */
    public static readFileMetadata(data: DriveReadFileMetadataData): CancelablePromise<DriveReadFileMetadataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/drive/files/{file_id}',
            path: {
                file_id: data.fileId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PresetsService {
    /**
     * Read Presets
     * List all convention presets (any authenticated user).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ConventionPresetsPublic Successful Response
     * @throws ApiError
     */
    public static readPresets(data: PresetsReadPresetsData = {}): CancelablePromise<PresetsReadPresetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/presets/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Preset
     * Create a convention preset (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ConventionPresetPublic Successful Response
     * @throws ApiError
     */
    public static createPreset(data: PresetsCreatePresetData): CancelablePromise<PresetsCreatePresetResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/presets/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Preset
     * Update a convention preset (admin only).
     * @param data The data for the request.
     * @param data.presetId
     * @param data.requestBody
     * @returns ConventionPresetPublic Successful Response
     * @throws ApiError
     */
    public static updatePreset(data: PresetsUpdatePresetData): CancelablePromise<PresetsUpdatePresetResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/presets/{preset_id}',
            path: {
                preset_id: data.presetId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Preset
     * Delete a convention preset (admin only).
     * @param data The data for the request.
     * @param data.presetId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deletePreset(data: PresetsDeletePresetData): CancelablePromise<PresetsDeletePresetResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/presets/{preset_id}',
            path: {
                preset_id: data.presetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RenameService {
    /**
     * Rename Preview
     * Generate rename previews for all files in a folder.
     *
     * Any authenticated user can call this (including Viewer for demo purposes).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RenamePreviewResponse Successful Response
     * @throws ApiError
     */
    public static renamePreview(data: RenameRenamePreviewData): CancelablePromise<RenameRenamePreviewResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rename/preview',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Rename Confirm
     * Execute file renames on Google Drive.
     *
     * Admin and User roles only. Viewer cannot confirm renames.
     * Partial confirmation: send only the files you want renamed.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RenameConfirmResponse Successful Response
     * @throws ApiError
     */
    public static renameConfirm(data: RenameRenameConfirmData): CancelablePromise<RenameRenameConfirmResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rename/confirm',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ServiceAccountsService {
    /**
     * Read Service Accounts
     * List all service accounts (admin only).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ServiceAccountsPublic Successful Response
     * @throws ApiError
     */
    public static readServiceAccounts(data: ServiceAccountsReadServiceAccountsData = {}): CancelablePromise<ServiceAccountsReadServiceAccountsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/service-accounts/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Service Account
     * Create a service account and assign to a user (admin only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ServiceAccountPublic Successful Response
     * @throws ApiError
     */
    public static createServiceAccount(data: ServiceAccountsCreateServiceAccountData): CancelablePromise<ServiceAccountsCreateServiceAccountResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/service-accounts/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Own Service Account
     * Get the service account assigned to the current user.
     * @returns ServiceAccountPublicWithEmail Successful Response
     * @throws ApiError
     */
    public static readOwnServiceAccount(): CancelablePromise<ServiceAccountsReadOwnServiceAccountResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/service-accounts/me'
        });
    }
    
    /**
     * Read Service Account
     * Get a specific service account by ID (admin only).
     * @param data The data for the request.
     * @param data.saId
     * @returns ServiceAccountPublic Successful Response
     * @throws ApiError
     */
    public static readServiceAccount(data: ServiceAccountsReadServiceAccountData): CancelablePromise<ServiceAccountsReadServiceAccountResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/service-accounts/{sa_id}',
            path: {
                sa_id: data.saId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Service Account
     * Update a service account (admin only).
     * @param data The data for the request.
     * @param data.saId
     * @param data.requestBody
     * @returns ServiceAccountPublic Successful Response
     * @throws ApiError
     */
    public static updateServiceAccount(data: ServiceAccountsUpdateServiceAccountData): CancelablePromise<ServiceAccountsUpdateServiceAccountResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/service-accounts/{sa_id}',
            path: {
                sa_id: data.saId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Service Account
     * Delete a service account (admin only).
     * @param data The data for the request.
     * @param data.saId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteServiceAccount(data: ServiceAccountsDeleteServiceAccountData): CancelablePromise<ServiceAccountsDeleteServiceAccountResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/service-accounts/{sa_id}',
            path: {
                sa_id: data.saId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Limits
     * Get rate limits for a user (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @returns UserLimitPublic Successful Response
     * @throws ApiError
     */
    public static readUserLimits(data: UsersReadUserLimitsData): CancelablePromise<UsersReadUserLimitsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}/limits',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User Limits
     * Set rate limits for a user (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserLimitPublic Successful Response
     * @throws ApiError
     */
    public static updateUserLimits(data: UsersUpdateUserLimitsData): CancelablePromise<UsersUpdateUserLimitsResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/{user_id}/limits',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Usage
     * Get usage summary for a user (admin only).
     * @param data The data for the request.
     * @param data.userId
     * @returns UsageSummary Successful Response
     * @throws ApiError
     */
    public static readUserUsage(data: UsersReadUserUsageData): CancelablePromise<UsersReadUserUsageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}/usage',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}