// This file is auto-generated by @hey-api/openapi-ts

export type ActivityAction = 'login' | 'logout' | 'rename' | 'settings_change' | 'user_created' | 'user_deleted' | 'limit_changed' | 'api_key_changed';

export type ActivityLogPublic = {
    id: string;
    user_id: string;
    user_email?: (string | null);
    action: ActivityAction;
    detail?: (string | null);
    tokens_used?: (number | null);
    created_at?: (string | null);
};

export type ActivityLogResponse = {
    data: Array<ActivityLogPublic>;
    count: number;
};

export type AdminSettingsPublic = {
    default_max_requests_per_day?: (number | null);
    default_max_tokens_per_month?: (number | null);
};

export type AdminSettingsUpdate = {
    default_max_requests_per_day?: (number | null);
    default_max_tokens_per_month?: (number | null);
};

export type ApiKeySetRequest = {
    api_key: string;
};

export type ApiKeyStatus = {
    is_set: boolean;
    masked_key?: (string | null);
    source?: string;
};

export type ApiKeyValidateResponse = {
    valid: boolean;
    error?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ConventionPresetCreate = {
    name: string;
    convention: string;
    description?: (string | null);
    content_type?: (string | null);
};

export type ConventionPresetPublic = {
    name: string;
    convention: string;
    description?: (string | null);
    content_type?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ConventionPresetsPublic = {
    data: Array<ConventionPresetPublic>;
    count: number;
};

export type ConventionPresetUpdate = {
    name?: (string | null);
    convention?: (string | null);
    description?: (string | null);
    content_type?: (string | null);
};

export type DriveFile = {
    id: string;
    name: string;
    mime_type: string;
    size?: (string | null);
    modified_time?: (string | null);
    thumbnail_url?: (string | null);
};

export type DriveFileList = {
    files: Array<DriveFile>;
};

export type DriveFolder = {
    id: string;
    name: string;
    created_time?: (string | null);
};

export type DriveFolderList = {
    folders: Array<DriveFolder>;
};

export type DriveFolderSearchResult = {
    id: string;
    name: string;
    parent_name?: (string | null);
};

export type DriveFolderSearchResultList = {
    results: Array<DriveFolderSearchResult>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RenameConfirmItem = {
    file_id: string;
    new_name: string;
    original_name?: string;
};

export type RenameConfirmRequest = {
    folder_id: string;
    renames: Array<RenameConfirmItem>;
};

export type RenameConfirmResponse = {
    results: Array<RenameResult>;
};

export type RenameHistoryResponse = {
    data: Array<RenameLogPublic>;
    count: number;
};

export type RenameLogPublic = {
    id: string;
    user_id: string;
    folder_id: string;
    original_name: string;
    new_name: string;
    created_at?: (string | null);
};

export type RenamePreview = {
    file_id: string;
    original_name: string;
    proposed_name: string;
    error?: (string | null);
};

export type RenamePreviewRequest = {
    folder_id: string;
    convention: string;
    instruction?: (string | null);
    content_type?: (string | null);
};

export type RenamePreviewResponse = {
    previews: Array<RenamePreview>;
};

export type RenameResult = {
    file_id: string;
    success: boolean;
    error?: (string | null);
};

export type ResetPassword = {
    new_password: string;
};

export type ServiceAccountCreate = {
    display_name: string;
    description?: (string | null);
    credentials_json: string;
    user_id: string;
};

export type ServiceAccountPublic = {
    display_name: string;
    description?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
};

export type ServiceAccountPublicWithEmail = {
    display_name: string;
    description?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
    client_email?: (string | null);
};

export type ServiceAccountsPublic = {
    data: Array<ServiceAccountPublic>;
    count: number;
};

export type ServiceAccountUpdate = {
    display_name?: (string | null);
    description?: (string | null);
    credentials_json?: (string | null);
    user_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UsageSummary = {
    requests_today: number;
    tokens_this_month: number;
    limit?: (UserLimitPublic | null);
};

export type UsageSummaryAdmin = {
    current_month_tokens: number;
    previous_month_tokens: number;
    all_time_tokens: number;
    current_month_cost: number;
    previous_month_cost: number;
    all_time_cost: number;
};

export type UsageTimeseriesPoint = {
    date: string;
    input_tokens: number;
    output_tokens: number;
    total_tokens: number;
    cost: number;
    request_count: number;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

export type UserLimitPublic = {
    max_requests_per_day?: (number | null);
    max_tokens_per_month?: (number | null);
};

export type UserLimitUpdate = {
    max_requests_per_day?: (number | null);
    max_tokens_per_month?: (number | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'admin' | 'user' | 'viewer';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminReadUsageSummaryResponse = (UsageSummaryAdmin);

export type AdminReadUsageTimeseriesData = {
    period?: string;
    range?: string;
};

export type AdminReadUsageTimeseriesResponse = (Array<UsageTimeseriesPoint>);

export type AdminReadUserUsageTimeseriesData = {
    period?: string;
    range?: string;
    userId: string;
};

export type AdminReadUserUsageTimeseriesResponse = (Array<UsageTimeseriesPoint>);

export type AdminReadUserUsageSummaryData = {
    userId: string;
};

export type AdminReadUserUsageSummaryResponse = (UsageSummary);

export type AdminReadUserActivityData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type AdminReadUserActivityResponse = (RenameHistoryResponse);

export type AdminReadActivityLogData = {
    action?: (ActivityAction | null);
    fromDate?: (string | null);
    limit?: number;
    skip?: number;
    toDate?: (string | null);
    userId?: (string | null);
};

export type AdminReadActivityLogResponse = (ActivityLogResponse);

export type AdminExportActivityData = {
    fromDate?: (string | null);
    toDate?: (string | null);
    userId?: (string | null);
};

export type AdminExportActivityResponse = (unknown);

export type AdminReadApiKeyStatusResponse = (ApiKeyStatus);

export type AdminUpdateApiKeyData = {
    requestBody: ApiKeySetRequest;
};

export type AdminUpdateApiKeyResponse = (ApiKeyStatus);

export type AdminRemoveApiKeyResponse = ({
    [key: string]: (string);
});

export type AdminValidateApiKeyData = {
    requestBody: ApiKeySetRequest;
};

export type AdminValidateApiKeyResponse = (ApiKeyValidateResponse);

export type AdminReadAdminSettingsResponse = (AdminSettingsPublic);

export type AdminUpdateSettingsData = {
    requestBody: AdminSettingsUpdate;
};

export type AdminUpdateSettingsResponse = (AdminSettingsPublic);

export type DriveReadFoldersResponse = (DriveFolderList);

export type DriveSearchDriveFoldersData = {
    q: string;
};

export type DriveSearchDriveFoldersResponse = (DriveFolderSearchResultList);

export type DriveReadFolderSubfoldersData = {
    folderId: string;
};

export type DriveReadFolderSubfoldersResponse = (DriveFolderList);

export type DriveReadFolderFilesData = {
    folderId: string;
};

export type DriveReadFolderFilesResponse = (DriveFileList);

export type DriveReadFileMetadataData = {
    fileId: string;
};

export type DriveReadFileMetadataResponse = (DriveFile);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshAccessTokenResponse = (Token);

export type LoginLogoutResponse = (Message);

export type LoginTestTokenResponse = (UserPublic);

export type PresetsReadPresetsData = {
    limit?: number;
    skip?: number;
};

export type PresetsReadPresetsResponse = (ConventionPresetsPublic);

export type PresetsCreatePresetData = {
    requestBody: ConventionPresetCreate;
};

export type PresetsCreatePresetResponse = (ConventionPresetPublic);

export type PresetsUpdatePresetData = {
    presetId: string;
    requestBody: ConventionPresetUpdate;
};

export type PresetsUpdatePresetResponse = (ConventionPresetPublic);

export type PresetsDeletePresetData = {
    presetId: string;
};

export type PresetsDeletePresetResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RenameRenamePreviewData = {
    requestBody: RenamePreviewRequest;
};

export type RenameRenamePreviewResponse = (RenamePreviewResponse);

export type RenameRenameConfirmData = {
    requestBody: RenameConfirmRequest;
};

export type RenameRenameConfirmResponse = (RenameConfirmResponse);

export type RenameReadRenameHistoryData = {
    limit?: number;
    skip?: number;
};

export type RenameReadRenameHistoryResponse = (RenameHistoryResponse);

export type ServiceAccountsReadServiceAccountsData = {
    limit?: number;
    skip?: number;
};

export type ServiceAccountsReadServiceAccountsResponse = (ServiceAccountsPublic);

export type ServiceAccountsCreateServiceAccountData = {
    requestBody: ServiceAccountCreate;
};

export type ServiceAccountsCreateServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsReadOwnServiceAccountResponse = (ServiceAccountPublicWithEmail);

export type ServiceAccountsReadServiceAccountData = {
    saId: string;
};

export type ServiceAccountsReadServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsUpdateServiceAccountData = {
    requestBody: ServiceAccountUpdate;
    saId: string;
};

export type ServiceAccountsUpdateServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsDeleteServiceAccountData = {
    saId: string;
};

export type ServiceAccountsDeleteServiceAccountResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserMeUsageResponse = (UsageSummary);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersResetUserPasswordData = {
    requestBody: ResetPassword;
    userId: string;
};

export type UsersResetUserPasswordResponse = (Message);

export type UsersReadUserLimitsData = {
    userId: string;
};

export type UsersReadUserLimitsResponse = (UserLimitPublic);

export type UsersUpdateUserLimitsData = {
    requestBody: UserLimitUpdate;
    userId: string;
};

export type UsersUpdateUserLimitsResponse = (UserLimitPublic);

export type UsersReadUserUsageData = {
    userId: string;
};

export type UsersReadUserUsageResponse = (UsageSummary);

export type UtilsHealthCheckResponse = (boolean);