// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DriveFile = {
    id: string;
    name: string;
    mime_type: string;
    size?: (string | null);
    modified_time?: (string | null);
    thumbnail_url?: (string | null);
};

export type DriveFileList = {
    files: Array<DriveFile>;
};

export type DriveFolder = {
    id: string;
    name: string;
    created_time?: (string | null);
};

export type DriveFolderList = {
    folders: Array<DriveFolder>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ServiceAccountCreate = {
    display_name: string;
    description?: (string | null);
    credentials_json: string;
    user_id: string;
};

export type ServiceAccountPublic = {
    display_name: string;
    description?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
};

export type ServiceAccountPublicWithEmail = {
    display_name: string;
    description?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
    client_email?: (string | null);
};

export type ServiceAccountsPublic = {
    data: Array<ServiceAccountPublic>;
    count: number;
};

export type ServiceAccountUpdate = {
    display_name?: (string | null);
    description?: (string | null);
    credentials_json?: (string | null);
    user_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'admin' | 'user' | 'viewer';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DriveReadFoldersResponse = (DriveFolderList);

export type DriveReadFolderFilesData = {
    folderId: string;
};

export type DriveReadFolderFilesResponse = (DriveFileList);

export type DriveReadFileMetadataData = {
    fileId: string;
};

export type DriveReadFileMetadataResponse = (DriveFile);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ServiceAccountsReadServiceAccountsData = {
    limit?: number;
    skip?: number;
};

export type ServiceAccountsReadServiceAccountsResponse = (ServiceAccountsPublic);

export type ServiceAccountsCreateServiceAccountData = {
    requestBody: ServiceAccountCreate;
};

export type ServiceAccountsCreateServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsReadOwnServiceAccountResponse = (ServiceAccountPublicWithEmail);

export type ServiceAccountsReadServiceAccountData = {
    saId: string;
};

export type ServiceAccountsReadServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsUpdateServiceAccountData = {
    requestBody: ServiceAccountUpdate;
    saId: string;
};

export type ServiceAccountsUpdateServiceAccountResponse = (ServiceAccountPublic);

export type ServiceAccountsDeleteServiceAccountData = {
    saId: string;
};

export type ServiceAccountsDeleteServiceAccountResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);