"""add cascade delete to refresh token

Revision ID: cc713b150da9
Revises: 2caca7609735
Create Date: 2026-04-02 19:24:06.532532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc713b150da9'
down_revision = '2caca7609735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refreshtoken_user_id_fkey'), 'refreshtoken', type_='foreignkey')
    op.create_foreign_key(None, 'refreshtoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtoken', type_='foreignkey')
    op.create_foreign_key(op.f('refreshtoken_user_id_fkey'), 'refreshtoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
